#!/bin/bash
# start java run for indexer classes and source data files

set -e

if [[ "$VERBOSE" == "yes" ]]; then
    set -x
fi

# check if the first argument starts with a hyphen
if [ "${1:0:1}" == '-' ]; then
    set -- docker-run "$@"
fi

exec "$@"