FROM replace-this-with-real-version
ARG committer_type
ARG dl_filename
ARG committer_version
ARG build_version
ARG crawler_type

WORKDIR $NORCONEX_HOME

#COPY downloaded/$committer_type/nx-committer-${committer_type}-${build_version}-202*.zip .
COPY downloaded/$committer_type/*.zip .

#RUN unzip nx-committer*

RUN ls ${dl_filename}

RUN unzip ${dl_filename}
#RUN cp nx-committer-${committer_type}-${committer_version}/lib/* nx-crawler-${crawler_type}-${build_version}-SNAPSHOT/lib/

#RUN ls $COLLECTOR_HOME/lib
#RUN cp nx-committer-${committer_type}-${committer_version}/lib/* $COLLECTOR_HOME/lib/
#RUN rm *.zip
