FROM replace-this-with-real-version
ARG committer_type
ARG dl_filename
ARG committer_version
ARG build_version
ARG crawler_type

WORKDIR $NORCONEX_HOME

COPY downloaded/$committer_type/*.zip .

RUN unzip ${dl_filename}; \
    cp nx-committer-${committer_type}-${committer_version}/lib/* ${COLLECTOR_HOME}/lib/

RUN if [ "$crawler_type" = "web" ]; then \
        mv ${COLLECTOR_HOME}/lib/jetty-alpn-client-11.0.15.jar jetty-alpn-client-11.0.15.jar1; \                
        mv ${COLLECTOR_HOME}/lib/jetty-client-11.0.15.jar jetty-client-11.0.15.jar1 ; \
        mv ${COLLECTOR_HOME}/lib/jetty-http-11.0.15.jar jetty-http-11.0.15.jar1 ; \
        mv ${COLLECTOR_HOME}/lib/jetty-io-11.0.15.jar jetty-io-11.0.15.jar1 ; \
        ls -l ${COLLECTOR_HOME}/lib/*jetty* ; \
    fi

RUN rm *.zip
