FROM ubuntu:22.04 AS base
ARG crawler_type
ARG build_version
ARG dl_filename

ENV COLLECTOR_HOME=/nxer/collector \
	WORKDIR=/nxer/outputs/workdir \
    COLLECTOR_LOG_DIR=/nxer/collector/logs \
	NORCONEX_HOME=/nxer \
	COLLECTOR_CONFIG_FILE=crawler-config.xml \	
    PATH="/nxer/collector:/nxer/docker-scripts:$PATH"

WORKDIR $NORCONEX_HOME

COPY .github/workflows/docker-scripts ./docker-scripts
COPY .github/workflows/support-files/ .
RUN mv crawler-config.xml $COLLECTOR_HOME/configs/

RUN ls; \
    echo ""; \
    ls docker-scripts; \
    ls $COLLECTOR_HOME/configs

RUN apt-get -y update ; \
    apt-get install -y nano ; \
    apt-get install -y curl ; \
    apt-get install -y unzip ; \
    apt-get install -y iputils-ping ; \
    apt install bash-completion ; \
    curl -LO https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.deb ; \
    dpkg -i jdk-17_linux-x64_bin.deb ; \    
    rm *.deb;

# Extract, remove carriage return in files and change permission
RUN set -x; \    
    sed -i -e 's/\r$//' docker-scripts/docker-entrypoint; \
    sed -i -e 's/\r$//' docker-scripts/docker-run; \
    chmod 755 docker-scripts/*; 

FROM base AS regular
WORKDIR $NORCONEX_HOME

COPY downloaded/$crawler_type/*.zip .
RUN unzip ${dl_filename}; \
    mv nx-crawler-${crawler_type}-${build_version} ${COLLECTOR_HOME}; \
    mv log4j*.jar ${COLLECTOR_HOME}/lib;
RUN chmod +x ${COLLECTOR_HOME}/crawl-${crawler_type}.*
RUN rm *.zip


FROM base AS snapshot
WORKDIR $NORCONEX_HOME

COPY downloaded/$crawler_type/*.zip .
RUN unzip ${dl_filename}; \
    cp -R nx-crawler-${crawler_type}-${build_version}-SNAPSHOT/* ${COLLECTOR_HOME}; \
    mv log4j*.jar ${COLLECTOR_HOME}/lib; \
    chmod +x ${COLLECTOR_HOME}/crawl-${crawler_type}.*; \
    rm *.zip; \
    rm -r nx-crawler-${crawler_type}-${build_version}-SNAPSHOT;

# Entry point when running docker container
ENTRYPOINT ["docker-entrypoint"]

# The run script
CMD ["docker-run"]