name: autoupdate
on:
  push: {}
    # branches:
    #     - main

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        id: autoupdate
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        #   DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
        #   MERGE_CONFLICT_ACTION: "fail"
          PR_READY_STATE: "ready_for_review"

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}