name: Download Latest Zip File from Newest Folder

on:
  workflow_dispatch:
    inputs:
      committer_type:
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and download zip file from newest folder
        run: |
          # Define URL of the page containing the list of folders
          base_url="https://repo1.maven.org/maven2/com/norconex/collectors/norconex-committer-${{inputs.committer_type}}/"

          # Extract the list of folder base_urls from the page
          all_folders=$(curl -s "$base_url" | grep -oP '(?<=href=")[^"]+/' | sort -r)

          # Get the URL of the newest folder
          newest_folder_url=$(echo "$all_folders" | head -n 1)

          echo "newest folder is: $newest_folder_url"

          # remove tailing slash from folder name as this is being used as part of the file name
          local_file_version_no="${newest_folder_url%/}"

          echo "local_file_version_no: $local_file_version_no"
          echo "file_version_no=$local_file_version_no" >> $GITHUB_ENV

          # construct the download url of the zip file
          local_zip_file_url="${base_url}${newest_folder_url}norconex-committer-${{inputs.committer_type}}-$local_file_version_no.zip"
          echo "zip_file_url=$local_zip_file_url" >> $GITHUB_ENV
          

          echo "zip file url: $zip_file_url"
          
          #curl -L -o latest.zip "$ZIP_FILE_URL"

          # Unzip the downloaded file
          #unzip latest.zip


      - name: print env variables
        run: |
          echo "env zip_file_url: ${{ env.zip_file_url}}"
          echo "env file_version_no: ${{env.file_version_no}}"