name: Owner check

# name: Test Merge Main into Branches

on:
    workflow_dispatch:

jobs:
  test-merge:
    runs-on: ubuntu-latest

    steps:
        - name: setup env
          run: |
            sudo apt install mailutils -y
            echo "my test file" >> testfile.txt
            
            mail -s "Test Email" -A testfile.txt brian.yuen@norconex.com
        
        
        
        
        
        
        
        
        
        
        
        ## Get the committers name from a branch
        # - name: Install Git
        #   run: sudo apt-get install git -y

        # - name: Fetch all branches
        #   run: |
        #     git clone https://github.com/brian-yuen/crawlers.git
        #     cd crawlers
            
        #     COMMIT_AUTHOR=$(git log remotes/origin/main | grep Author | sed 's/.*Author: \(.*\) <.*/\1/' | awk '{print $1}' | sort -u)
            
        #     for commit in $COMMIT_AUTHOR; do
        #         echo "Commit author: $commit"
        #     done

    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #     with:
    #         ref: uv-kafka

    #   - name: find out last committer
    #     run: |
    #       COMMIT_AUTHOR=$(git log uv-kafka --not main)
    #       for commit in $COMMIT_AUTHOR; do
    #         echo "Commit author: $commit"
    #       done