name: Owner check

# name: Test Merge Main into Branches

on:
    push:
        branches:
          - main

    workflow_dispatch:

jobs:
  test-merge:
    runs-on: ubuntu-latest

    steps:
        # - uses: actions/checkout@v4
        #   with:
        #     fetch-depth: 0

        - name: Fetch all branches
          run: |
            git clone https://github.com/brian-yuen/crawlers.git
            mv crawlers /home/runner/work/crawlers/
            cd /home/runner/work/crawlers/crawlers            
            git config user.name "GitHub Action"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
            git checkout main


        - name: Get modified files           
          id: modified-files        
          uses: tj-actions/changed-files@v42.0.5
          with:
            files_ignore: |     
              # ignore the yml files and header files in the github folder       
              .github/workflows/copyright-headers/*.txt
              .github/workflows/*.yml
              .github/*.yml
              **/assembly/**

        - name: display result
          run: |
            echo "result: ${{steps.modified-files.outputs.all_changed_files}}"

        - name: Test
          if: steps.modified-files.outputs.any_changed == 'true'
          run: |
            # git clone https://github.com/brian-yuen/crawlers.git
            # mv crawlers /home/runner/work/crawlers/
            # cd /home/runner/work/crawlers/crawlers
            
            COMMIT_AUTHORS=$(git log remotes/origin/main --format='%ae' | sort -u | grep 'gmail\|norconex')
            
            for author in $COMMIT_AUTHORS; do
                echo "Commit author: $author"
            done
        



        
        
        
        
        
        
        
        
        
        
        
        ## Get the committers name from a branch
        # - name: Install Git
        #   run: sudo apt-get install git -y

        # - name: Fetch all branches
        #   run: |
        #     git clone https://github.com/brian-yuen/crawlers.git
        #     cd crawlers
            
        #     COMMIT_AUTHOR=$(git log remotes/origin/main | grep Author | sed 's/.*Author: \(.*\) <.*/\1/' | awk '{print $1}' | sort -u)
            
        #     for commit in $COMMIT_AUTHOR; do
        #         echo "Commit author: $commit"
        #     done

    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #     with:
    #         ref: uv-kafka

    #   - name: find out last committer
    #     run: |
    #       COMMIT_AUTHOR=$(git log uv-kafka --not main)
    #       for commit in $COMMIT_AUTHOR; do
    #         echo "Commit author: $commit"
    #       done