name: Owner check

# name: Test Merge Main into Branches

on:
    workflow_dispatch:

jobs:
  test-merge:
    runs-on: ubuntu-latest

    steps:
        - name: Install Git
          run: sudo apt-get install git -y

        - name: Fetch all branches
          run: |
            git clone https://github.com/brian-yuen/crawlers.git
            cd crawlers
            
            COMMIT_AUTHOR=$(git log remotes/origin/main | grep Author | sed 's/.*Author: \(.*\) <.*/\1/' | sort -u)
            
            for commit in $COMMIT_AUTHOR; do
                echo "Commit author: $commit"
            done

    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #     with:
    #         ref: uv-kafka

    #   - name: find out last committer
    #     run: |
    #       COMMIT_AUTHOR=$(git log uv-kafka --not main)
    #       for commit in $COMMIT_AUTHOR; do
    #         echo "Commit author: $commit"
    #       done