name: Check Branch Sync

on:
  push:
    branches:
      - main

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get install git -y

      - name: Fetch all branches
        run: git fetch --all

      - name: Check branch sync
        run: |
          for branch in $(git branch -r --format '%(refname:short)'); do
            if [[ $branch != "origin/2.x-branch" && $branch != "origin/3.x-branch" ]]; then
              git checkout $branch
              git pull origin $branch
              if [[ $(git merge-base HEAD origin/main) == $(git rev-parse HEAD) ]]; then
                echo "Branch $branch is up to date with main branch"
                # Send email to branch owner
                # Replace 'send-email-command' with actual command to send email
                # Replace 'branch-owner-email' with actual email of branch owner
                send-email-command "Your branch $branch can merge with the main branch, please go ahead and do so." branch-owner-email
              else
                echo "Branch $branch has conflicts with the main branch"
                # Send email to branch owner
                # Replace 'send-email-command' with actual command to send email
                # Replace 'branch-owner-email' with actual email of branch owner
                send-email-command "Your branch $branch has conflicts with the main branch, please resolve the conflict and then sync with the main branch." branch-owner-email
              fi
            fi
          done



# name: Update Branch

# on:
#   push:
#     branches: [main]
    
# permissions: 
#   contents: write

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Setup Git User
#         run: |
#           git config user.name "GitHub Action"
#           git config user.email "brian.yuen@norconex.com"

#       - name: Update Branch
#         run: |
#           git checkout main
#           git fetch origin
#           git checkout update-test
#           git pull
#           git merge origin/main
#           git push origin update-test