name: Update Branch

on:
  push:
    branches: [main]
    
permissions: 
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "brian.yuen@norconex.com"

      - name: Update Branch
        run: |
          git checkout main
          git fetch origin
          git checkout update-test
          git pull
          git merge origin/main
          git push origin update-test